import type { Metadata } from "next";

import "./globals.css";
import AuthProvider from "../components/provider/AuthProvider";
import Navigation from "../components/navigation";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="flex flex-row w-screen h-screen">
        <ToastContainer position="top-right" autoClose={1500}/>
          <AuthProvider>
            <Navigation />
            <div className="w-screen flex-grow ml-44 overflow-y-auto">
              {children}
            </div>
          </AuthProvider>
      </body>
    </html>
  );
}
